kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysis
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: http://argoisdfull.ninja-test.opsmx.net/
          application: newapp21
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          user: admin
          lifetimeMinutes: 6
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: splunktemp
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "Splunklogservice"
          - metricTemplateName: datadogtemp
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            serviceName: "datadogmetricservice"
            
            
            
