apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testappss
spec:
  metrics:
    - name: testappss
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          user: admin
          application: argocd-qa01-newrelicmetric
          baselineStartTime: "2022-09-26T04:17:00.002Z"
          canaryStartTime: "2022-09-26T04:17:00.002Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: newrelicmetrictemp01
            metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "issugen-baseline,{{args.baseline-hash}}"
            canaryMetricScope: "issugen-canary,{{args.canary-hash}}"
