apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: datadogtestapp
spec:
  metrics:
    - name: datadogtestapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argo.isd.demoserver.opsmx.net/
          user: admin
          application: tejaapp19
          baselineStartTime: "2022-11-03T11:29:46.915Z"
          canaryStartTime: "2022-11-03T11:29:46.915Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: datadoglogtemplate
            logScopeVariables: " kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"
            serviceName: "dogservicewithlogtemplate"
