apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argorolltest
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argorolltest
  template:
    metadata:   
      labels:
        app: argorolltest
    spec:
      containers:
        - name: rollouts-demo-exp
          image: docker.io/opsmxdev/issuegen:v3.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : argorolltest
                requiredForCompletion: true
                templateName: testapp
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
        - setWeight: 50
        - pause: { duration: 45s }
        - experiment:
            analyses:
              - name : testapp
                requiredForCompletion: true
                templateName: testapp
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
