apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testappss
spec:
  metrics:
    - name: testappss
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: http://argoisdfull.ninja-test.opsmx.net/
          user: admin
          application: elasticapp27
          baselineStartTime: "2022-09-16T06:10:00Z"
          canaryStartTime: "2022-09-19T08:06:00Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: stackdrivertemplate
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "StackDriverService1"
          - logTemplateName: elastictemplate
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "ElasticSearchService1"
          - logTemplateName: stackdrivertemplate
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "StackDriverService2"
          - logTemplateName: elastictemplate
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "ElasticSearchService2"
          - logTemplateName: elastictemplate
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "ElasticSearchService3"
          - logTemplateName: elastictemplate
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "ElasticSearchService4"
          - logTemplateName: elastictemplate
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "ElasticSearchService5"
          - logTemplateName: stackdrivertemplate
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "StackDriverService3"
          - logTemplateName: stackdrivertemplate
            logScopeVariables: "resource.labels.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            serviceName: "StackDriverService4"

