apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argo17.ninja-test.opsmx.net/
          user: admin
          application: tejalogmetric
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: elasticlogtemplate
            metricScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
            metricTemplateName: elasticmetrictemplate
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
