apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testappss
spec:
  metrics:
    - name: testappss
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argocd17.ninja-test.opsmx.net/
          user: admin
          application: argocd-qa01-singleservice-logtemplate-splunk-teja-94013
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: spluncklogtemplet
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"
            serviceName: "splunkservicewithlogtemplate"      
